# Generated by Django 4.2 on 2025-03-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='noemail@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='ademola@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
