# Generated by Django 4.2 on 2025-05-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0006_community_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
