# Generated by Django 4.2 on 2025-05-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0007_community_member_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='max_members',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
