# Generated by Django 4.2 on 2025-05-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0008_community_max_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='community',
            name='member_count',
        ),
    ]
